[project]
name = "extract-invoices-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyperclip>=1.9.0",
    "tabulate>=0.9.0",
]
